import {buildModel,history,PRESETS,UNKNOWN,COMMIT} from './model.mjs';import {connect} from './sync.mjs';import {number,value,installNumeric} from './numeric-ui.mjs';import {explain} from './provenance.mjs';import {bindTerms,term,objectTerm,sourceFragment,explainTerm,registryReport} from './terminology.mjs';
const $=id=>document.getElementById(id),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cache=new Map(),model=p=>{if(!cache.has(p))cache.set(p,buildModel(p));return cache.get(p);},role=location.pathname.endsWith('visual.html')?'visual':'control';
const sources=await fetch('sources.json').then(r=>r.json());let lastPreset='',lastStep=-1,lastSignature='',current,api;
const brief=v=>{
 if(typeof v==='string')return v;
 if(Array.isArray(v)){if(v.some(x=>x&&typeof x==='object'))return `[${v.map(x=>x.dst_rank!==undefined?`SQE${x.physicalSQE}→R${x.dst_rank}/槽${x.dst_slot}; SGE=${x.SGEs.map(z=>z.bytes+'B').join('+')}`:brief(x)).join('; ')}]`;return v.length>8?`[${v.slice(0,4).join(', ')}, …] · 共 ${v.length} 元素`:JSON.stringify(v);}
 if(v&&typeof v==='object'){if(v.hidden)return `key=${v.key}; hidden=${brief(v.hidden)}; metadata按record布局；${v.status}`;const text=Object.entries(v).map(([k,x])=>`${k}=${brief(x)}`).join('; ');return text.length>85?text.slice(0,85)+'…（展开完整字段）':text;}
 return String(v);
};
const Q=(id,path=[],phase='auto',step=current.step)=>({objectId:id,elementPath:path,phase,step}),N=(id,v,extra={})=>number({objectId:id,value:v,step:current.step,...extra},v),V=(id,v,path=[],phase='auto',step=current.step,limit=4)=>value(Q(id,path,phase,step),v,{limit}),F=(m,k)=>N('@config.'+k,m.config[k]);let numeric;
const active=(f,id)=>f.writes.some(x=>x.id===id)||f.reads.some(x=>x.id===id);const operation=(f,id)=>f.writes.some(x=>x.id===id)?'写':f.reads.some(x=>x.id===id)?'读':'';
function cellButton(f,id,text,key,state){return `<button class="cellButton ${active(f,id)?'active':''} ${key===state.selected?'selected':''}" data-cell="${esc(id)}" ${key?`data-key="${key}"`:''} title="${esc(id)}">${active(f,id)?operation(f,id)+' ':''}${text}</button>`;}
function tokenSelect(s){const [r,t]=s.selected.split(':').map(Number);$('rank').value=r;$('token').value=t;}
function render(s){current=s;const signature=[s.preset,s.step,s.selected,s.cell,s.element,s.duration,s.playing].join('|');$('connection').textContent=s.authoritative?'权威控制页':s.connected?'已联动':'等待控制页';if(signature===lastSignature){if(role==='control')$('play').textContent=s.playing?'暂停':'播放';return;}const m=model(s.preset),f=m.frames[s.step];if(!f)return;
 const stepChanged=lastStep!==s.step||lastPreset!==s.preset;numeric?.close();lastSignature=signature;lastStep=s.step;
 $('stepLabel').innerHTML=`步骤 ${N('@index.step',s.step)} / ${N('@index.step',m.frames.length-1)}`;
 if(role==='control'){
  if(lastPreset!==s.preset){$('seek').max=m.frames.length-1;$('cell').innerHTML=Object.keys(m.ledger).map(id=>`<option value="${esc(id)}">${esc(id)}</option>`).join('');$('stageJump').innerHTML=m.frames.map((f,i)=>`<option value="${i}">${i} · ${esc(f.title)}</option>`).join('');}
  $('preset').value=s.preset;$('speed').value=s.duration;$('seek').value=s.step;$('stageJump').value=s.step;$('play').textContent=s.playing?'暂停':'播放';$('stageTitle').textContent=f.title;$('explanation').textContent=f.explanation;$('actors').innerHTML=f.actors.map(x=>`<span class="tag">${esc(x)}</span>`).join('');$('condition').textContent=f.condition;
  const variants=f.sources||[f.source];$('sourceTab').innerHTML=variants.map((x,i)=>`<option value="${i}">${x.fn} · L${x.start}–${x.end}</option>`).join('');const src=f.source;$('sourceMeta').innerHTML=`<b>${esc(src.fn)}</b> · 定义 L${src.def}<br>${esc(src.file)} · L${src.start}–${src.end}<br><span class="muted">${esc(src.caller)} · ${COMMIT.slice(0,12)}</span>`;
  $('code').innerHTML=sourceFragment(src.file,src.start,src.end,sources.files[src.file],{fn:src.fn,step:s.step,preset:s.preset}).map((line,i)=>`<div class="codeLine ${src.active.includes(src.start+i)?'executing':''}"><span class="lineNum">${src.start+i}</span><span class="sourceText">${line}</span></div>`).join('');
  $('fullSource').href=`source.html?file=${encodeURIComponent(src.file)}&line=${src.def}&preset=${s.preset}&step=${s.step}`;
  tokenSelect(s);$('element').value=s.element;const tok=m.tokens.find(t=>t.key===s.selected)||m.tokens[0];
  if(tok){$('tokenSummary').innerHTML=`源 R${N('@index.rank',tok.r)} token ${N('@index.token',tok.t)} / global_idx=${N('@metric.globalIdx',tok.gid,{sourceRank:tok.r,token:tok.t})}；topk_idx=${V(m.id(tok.r,'topk_idx',tok.t),tok.topk)}；x[${N('@index.token',tok.t)},${N('@index.hidden',s.element)}]=${V(m.id(tok.r,'x',tok.t),tok.x[s.element],[s.element])}。接收按来源rank分区，展开按expert分区。`;
   const dest=m.outputPlan.flatMap((a,dst)=>a.filter(r=>r.key===tok.key).map(rec=>({dst,rec})));const entries=[{id:m.id(tok.r,'x',tok.t),label:'x 输入',html:V(m.id(tok.r,'x',tok.t),tok.x[s.element],[s.element])},{id:m.id(tok.r,'dst_buffer_slot_idx',tok.t),label:'dst slot / gsge',html:V(m.id(tok.r,'dst_buffer_slot_idx',tok.t),f.snapshot[m.id(tok.r,'dst_buffer_slot_idx',tok.t)])+' / '+V(m.id(tok.r,'dst_gsge_idx',tok.t),f.snapshot[m.id(tok.r,'dst_gsge_idx',tok.t)])},{id:m.id(tok.r,'metadata_send_buffer',tok.t),label:'metadata_send',html:f.snapshot[m.id(tok.r,'metadata_send_buffer',tok.t)]===UNKNOWN?V(m.id(tok.r,'metadata_send_buffer',tok.t),UNKNOWN):F(m,'metadataBytes')+'B · '+(m.config.cached?'缓存无topk/global_idx':'topk='+V(m.id(tok.r,'metadata_send_buffer',tok.t),tok.topk,['topk'])+' · gid='+V(m.id(tok.r,'metadata_send_buffer',tok.t),tok.gid,['src_global_idx']))},...dest.map(({dst,rec})=>({id:m.id(dst,'recv_buffer',`${tok.r},${rec.slot}`),label:`R${dst} 接收槽`,html:f.snapshot[m.id(dst,'recv_buffer',`${tok.r},${rec.slot}`)]===UNKNOWN?V(m.id(dst,'recv_buffer',`${tok.r},${rec.slot}`),UNKNOWN):`slot ${N('@index.slot',rec.slot)} · hidden[${N('@index.hidden',s.element)}]=${V(m.id(dst,'recv_buffer',`${tok.r},${rec.slot}`),tok.x[s.element],['hidden',s.element])}`}))];
   $('trace').innerHTML=entries.map(e=>`<div class="traceLine ${active(f,e.id)?'active':''}" data-cell="${esc(e.id)}"><b>${esc(e.label)} ${operation(f,e.id)}</b><span>${e.html}</span></div>`).join('');
  }else{$('tokenSummary').innerHTML=`T=${F(m,'T')}：输入为空，${F(m,'C')} AIV空范围；接收和输出计数为${N('@metric.recvCount',0,{rank:0})}。`;$('trace').innerHTML='';}
  const cell=s.cell in m.ledger?s.cell:Object.keys(m.ledger)[0],l=m.ledger[cell];$('cell').value=cell;$('ledgerInfo').innerHTML=`${objectTerm(cell,{step:s.step,preset:s.preset})} · ${esc(l.owner)} · ${esc(l.memory)} · ${N('@dtype',l.dtype,{object:cell})} · shape=[${l.shape.map((n,i)=>N('@shape',n,{object:cell,index:i})).join(', ')}] · 容量${N('@bytes',l.bytes,{object:cell})}字节。${esc(l.note)}`;
  const v=f.snapshot[cell],element=l.obj==='x'||l.obj==='recv_x'?s.element:undefined,path=element===undefined?[]:[element],shown=Array.isArray(v)&&element!==undefined?v[element]:v,change=f.writes.find(x=>x.id===cell);
  $('currentValue').className='currentValue '+(active(f,cell)?'active':'');$('currentValue').innerHTML=change?`写：${V(cell,Array.isArray(change.before)&&element!==undefined?change.before[element]:change.before,path,'write-before')} → ${V(cell,Array.isArray(change.after)&&element!==undefined?change.after[element]:change.after,path,'write-after')}`:`${operation(f,cell)||'当前'}：${V(cell,shown,path)}`;
  const hs=history(m,cell,element).filter(h=>h.step<=s.step).slice(-8);$('history').innerHTML=hs.map(h=>`<div class="historyRow ${h.step===s.step?'now':''}"><span>步骤 ${N('@index.step',h.step)}</span><b>${h.op}</b><span>${V(cell,h.value,path,'history',h.step)}</span></div>`).join('');$('history').scrollTop=$('history').scrollHeight;
 }else{
  const c=m.config;$('visualConfig').innerHTML=`R=${F(m,'R')} · E=${F(m,'E')} · K=${F(m,'K')} · T=${F(m,'T')}/rank · M=${F(m,'M')} · H=${F(m,'H')} · A=${F(m,'A')} · ${c.cached?'cached':'fresh'} · ${c.fp8?'FP8 + '+F(m,'sfPacks')+' SF packs':'BF16，无SF'} · ${F(m,'C')} AIV/rank`;
  const tr=f.transfers.filter(t=>t.key===s.selected);$('transport').innerHTML=`<strong>${esc(f.title)}</strong><span class="op">${tr.length?tr.map(t=>`R${N('@index.rank',t.src)} → R${N('@index.rank',t.dst)} · 槽 ${N('@index.slot',t.slot)} · ${esc(t.kind)}`).join('；'):f.writes.length?`本步 ${N('@metric.accessCount',f.reads.length,{access:'read'})} 处读 / ${N('@metric.accessCount',f.writes.length,{access:'write'})} 处写`:'观察初始 / 完成结果'}</span>`;
  $('ranks').innerHTML=Array.from({length:4},(_,r)=>rankHTML(m,f,r,s)).join('');
 }
 bindTerms(document.querySelector('.app'),{step:s.step,preset:s.preset,stage:f.stage,surface:role});lastPreset=s.preset;if(stepChanged){const node=role==='control'?$('stageTitle'):$('transport');node.classList.remove('stagePulse');void node.offsetWidth;node.classList.add('stagePulse');}
}
function rankHTML(m,f,r,s){const c=m.config,id=m.id;let content='';const inputStages=['input','histogram','prefix','slots','restore','idle'];const sendStages=['metadata','sqe','local','issue'];
 const cv=(obj,index,path=[],limit=4)=>{const key=id(r,obj,index),v=f.snapshot[key];let x=v;for(const k of path)x=x===UNKNOWN?UNKNOWN:x[k];return V(key,x,path,'auto',s.step,limit);},idx=(kind,v)=>N('@index.'+kind,v),cb=(obj,index,html,key)=>cellButton(f,id(r,obj,index),html,key,s);
 if(inputStages.includes(f.stage)){
  content=`<div class="summary"><span>topk_idx[T,${F(m,'K')}] / x[T,${F(m,'H')}]</span><span>有效expert总计 ${N('@metric.sourceExpertHits',m.tokens.filter(t=>t.r===r).reduce((n,t)=>n+t.topk.filter(e=>e>=0).length,0),{rank:r})}</span></div><div class="row header"><span>token编号</span><span>expert IDs</span><span>x[token,0] / 载荷</span><span>dst slot / gsge</span></div>`;
  for(const t of m.tokens.filter(t=>t.r===r))content+=`<div class="row"><span>${idx('token',t.t)} · AIV ${idx('aiv',t.t)}</span>${cb('topk_idx',t.t,cv('topk_idx',t.t),t.key)}${cb('x',t.t,cv('x',t.t,[0])+' · '+F(m,'hiddenBytes')+'B',t.key)}${cb('dst_buffer_slot_idx',t.t,cv('dst_buffer_slot_idx',t.t)+' / '+cv('dst_gsge_idx',t.t),t.key)}</div>`;
  content+=cb('rank_histogram_sum_view',undefined,`rank计数 [目的 R${idx('rank',0)}…R${idx('rank',3)}] = ${cv('rank_histogram_sum_view')}`)+`<div class="formula">每token目标rank去重；local slot无SGE。<br>${F(m,'C')} AIV；空核仍发布count/arrival，逐核账本可查。</div>`;
 }else if(sendStages.includes(f.stage)){
  content=`<div class="summary"><span>metadata_send_buffer / SQE</span><span>hidden=${F(m,'hiddenBytes')}B · meta=${F(m,'metadataBytes')}B</span></div><div class="row header"><span>token编号</span><span>打包字段 / global</span><span>local_copy_dst_slot</span><span>remote SQE / SGE</span></div>`;
  for(const t of m.tokens.filter(t=>t.r===r)){const meta=f.snapshot[id(r,'metadata_send_buffer',t.t)],sq=f.snapshot[id(r,'SQE',t.t)];content+=`<div class="row"><span>${idx('token',t.t)} · AIV ${idx('aiv',t.t)}</span>${cb('metadata_send_buffer',t.t,meta===UNKNOWN?cv('metadata_send_buffer',t.t):c.cached?'weights='+cv('metadata_send_buffer',t.t,['weights']):'idx='+cv('metadata_send_buffer',t.t,['topk'])+'; g='+cv('metadata_send_buffer',t.t,['src_global_idx']),t.key)}${cb('local_copy_dst_slot_idx',t.t,cv('local_copy_dst_slot_idx',t.t),t.key)}${cb('SQE',t.t,sq===UNKNOWN?cv('SQE',t.t):N('@metric.sqeCount',sq.length,{tokenKey:t.key})+' SQE · '+N('@metric.sgeCount',sq.length*2,{tokenKey:t.key})+' SGE',t.key)}</div>`;}
  content+=cb('signals',undefined,`metadata_ready=${cv('signals',undefined,['metadata_ready'])} · local_copy_ready=${cv('signals',undefined,['local_copy_ready'])} · DB=${cv('signals',undefined,['doorbell'])}`)+`<div class="formula">remote offset=(来源rank×${F(m,'M')}+slot)×${F(m,'tokenBytes')}B。<br>SGE pair读hidden+metadata；完整SQE字段在账本。</div>`;
 }else if(['counts','receive','epPrefix'].includes(f.stage)){
  content=`<div class="summary"><span>接收槽 [来源rank,来源槽]</span><span>有效 ${N('@metric.recvCount',m.recvPlan[r].length,{rank:r})} / 容量${N('@metric.capacitySlots',16)} 条</span></div><div class="row header"><span>来源rank</span><span>slot → global_idx</span><span>x[token,0]</span><span>目标本地expert</span></div>`;
  for(let sr=0;sr<4;sr++){const recs=m.recvPlan[r].filter(t=>t.r===sr);content+=`<div class="row"><span>R${idx('rank',sr)}</span><span>${recs.length?recs.map(rec=>cb('recv_buffer',`${sr},${rec.slot}`,idx('slot',rec.slot)+'→'+N('@metric.globalIdx',rec.gid,{sourceRank:rec.r,token:rec.t}),rec.key)).join(''):'空peer'}</span><span>${recs.map(rec=>cv('recv_buffer',`${sr},${rec.slot}`,['hidden',0])).join(' / ')||'—'}</span><span>${recs.map(rec=>rec.topk.filter(e=>Math.floor(e/2)===r).map(e=>idx('expert',e)).join(',')).join(' / ')||'—'}</span></div>`;}
  content+=cb('psum_num_recv_tokens_per_rank',undefined,'来源rank包含前缀 = '+cv('psum_num_recv_tokens_per_rank'))+cb('psum_num_recv_tokens_per_expert',undefined,'expert raw end（含前面aligned） = '+cv('psum_num_recv_tokens_per_expert'))+`<div class="formula">record=${F(m,'tokenBytes')}B；source分区=${F(m,'regionBytes')}B；计数≠载荷就绪。</div>`;
 }else{
  content=`<div class="summary"><span>recv_x[${N('@metric.expandedCount',m.expanded[r],{rank:r})},${F(m,'H')}]</span><span>s=输出槽 · g=src_token_global_idx · x₀=首元素</span></div>`;
  for(let e=0;e<2;e++){const start=e===0?0:Math.ceil(m.prefixExpert[r][e-1]/c.A)*c.A,end=Math.ceil(m.prefixExpert[r][e]/c.A)*c.A;let tiles='';for(let slot=start;slot<end;slot++){const rec=m.outputPlan[r].find(rec=>rec.slots.includes(slot)),key=rec?.key;tiles+=`<button class="tile ${active(f,id(r,'recv_x',slot))?'active':''} ${key===s.selected?'selected':''}" data-cell="${esc(id(r,'recv_x',slot))}" ${key?`data-key="${key}"`:''}>s${idx('slot',slot)} ${rec?'g'+N('@metric.globalIdx',rec.gid,{sourceRank:rec.r,token:rec.t}):'pad'}<br>x₀=${cv('recv_x',slot,[0])}</button>`;}
   content+=`<div class="outputGroup"><span>expert ${idx('expert',r*2+e)}<br>raw=${N('@metric.expertCount',m.expertCounts[r][e],{rank:r,expert:e})}<br>start=${N('@metric.expertStart',start,{rank:r,expert:e})}</span><div class="tileGrid">${tiles||'<span>空expert</span>'}</div></div>`;}
  const rec=m.outputPlan[r].find(x=>x.key===s.selected);if(rec)content+=cb('recv_src_metadata',rec.pos,`流位置${idx('slot',rec.pos)} recv_src_metadata = ${cv('recv_src_metadata',rec.pos)}`,rec.key);
  content+=`<div class="formula">按local expert展开；一rank副本可复制到两个expert槽。完整字段与padding见账本。</div>`;
 }
 return `<article class="rankCard" style="--rank:${['#355d8c','#397565','#7a5d92','#977138'][r]}"><header class="rankTitle"><strong>Rank ${idx('rank',r)}</strong><span>负责 expert ${idx('expert',r*2)}、${idx('expert',r*2+1)} · ${c.cached?'cached':'fresh'}</span></header><div class="rankBody">${content}</div></article>`;
}
api=connect(role,p=>model(p).frames.length,render);window.dispatchDemo={api,model,history,explain,explainTerm,registryReport};numeric=installNumeric(()=>model(api.getState().preset));window.dispatchDemo.numeric=numeric;
const session=api.session;if(role==='control'){
 $('preset').innerHTML=Object.entries(PRESETS).map(([v,t])=>`<option value="${v}">${esc(t)}</option>`).join('');for(let r=0;r<4;r++)$('rank').add(new Option(`Rank ${r}`,r));for(let t=0;t<4;t++)$('token').add(new Option(`token ${t}`,t));
 $('sourceTab').onchange=()=>{const s=api.getState(),f=model(s.preset).frames[s.step],src=f.sources[+$('sourceTab').value];$('sourceMeta').innerHTML=`<b>${esc(src.fn)}</b> · 定义 L${src.def}<br>${esc(src.file)} · L${src.start}–${src.end}<br>${esc(src.caller)} · ${COMMIT.slice(0,12)}`;$('code').innerHTML=sourceFragment(src.file,src.start,src.end,sources.files[src.file],{fn:src.fn,step:s.step,preset:s.preset}).map((line,i)=>`<div class="codeLine ${src.active.includes(src.start+i)?'executing':''}"><span class="lineNum">${src.start+i}</span><span class="sourceText">${line}</span></div>`).join('');$('fullSource').href=`source.html?file=${encodeURIComponent(src.file)}&line=${src.def}&preset=${s.preset}&step=${s.step}`;bindTerms($('sourceMeta'),{step:s.step,preset:s.preset,fn:src.fn,surface:'source-meta'});};$('visualLink').href=`visual.html?session=${encodeURIComponent(session)}`;$('openVisual').onclick=()=>window.open($('visualLink').href,'deepep-visual-'+session);
 for(const [id,action,value]of[['play','play'],['previous','step',-1],['next','step',1],['reset','reset']])$(id).onclick=()=>api.send({action,value});
 $('speed').onchange=()=>api.send({action:'speed',value:+$('speed').value});$('preset').onchange=()=>api.send({action:'preset',value:$('preset').value});$('seek').oninput=()=>api.send({action:'seek',value:+$('seek').value});$('stageJump').onchange=()=>api.send({action:'seek',value:+$('stageJump').value});
 const pickToken=()=>{const r=+$('rank').value,t=+$('token').value;api.send({action:'select',key:`${r}:${t}`,cell:`R${r}.x[${t}]`});};$('rank').onchange=pickToken;$('token').onchange=pickToken;$('element').onchange=()=>api.send({action:'element',value:Math.max(0,Math.min(255,+$('element').value||0))});$('cell').onchange=()=>api.send({action:'cell',value:$('cell').value});
 $('inspect').onclick=()=>{numeric.close();const s=api.getState(),m=model(s.preset),f=m.frames[s.step],l=m.ledger[s.cell];$('dialogContent').innerHTML=`<p>${objectTerm(s.cell,{step:s.step,preset:s.preset,surface:'inspector'})} · dtype=${N('@dtype',l.dtype,{object:s.cell})} · shape=[${l.shape.map((n,i)=>N('@shape',n,{object:s.cell,index:i})).join(', ')}] · bytes=${N('@bytes',l.bytes,{object:s.cell})} · ${esc(l.memory)} · ${esc(l.owner)} · ${esc(l.note)}</p><h3>当前完整内容（每个元素可独立解释）</h3><div class="structuredValue">${V(s.cell,f.snapshot[s.cell],[],'auto',s.step,Infinity)}</div><h3>完整值历史（含所有256元素）</h3>${history(m,s.cell).map(h=>`<p>步骤${N('@index.step',h.step)} · ${esc(h.op)} · ${esc(h.title)}</p><div class="structuredValue">${V(s.cell,h.value,[],'history',h.step,Infinity)}</div>`).join('')}`;bindTerms($('dialogContent'),{objectId:s.cell,step:s.step,preset:s.preset,stage:f.stage,surface:'inspector'});$('inspector').showModal();};$('closeDialog').onclick=()=>{numeric.close();$('inspector').close();};$('inspector').addEventListener('close',()=>numeric.close());
 for(const [id,kind]of[['element','hidden'],['rank','rank'],['token','token'],['seek','step'],['stageJump','step']]){const el=$(id);el.dataset.numId='@index.'+kind;el.dataset.numPath='[]';el.onfocus=()=>{el.dataset.numQuery=JSON.stringify({objectId:'@index.'+kind,value:+el.value,elementPath:[],step:api.getState().step,phase:'observe'});};}
 $('speed').dataset.numId='@control.speed';$('speed').dataset.numPath='[]';$('speed').onfocus=()=>{$('speed').dataset.numQuery=JSON.stringify({objectId:'@control.speed',value:+$('speed').value,elementPath:[],step:api.getState().step,phase:'observe'});};
}else $('controlLink').href=`control.html?session=${encodeURIComponent(session)}`;
$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'退出全屏':'全屏';});
document.body.addEventListener('click',ev=>{const el=ev.target.closest('[data-cell]');if(!el)return;api.send(el.dataset.key?{action:'select',key:el.dataset.key,cell:el.dataset.cell}:{action:'cell',value:el.dataset.cell});});
const hint=document.createElement('span');hint.className='numericHint';hint.textContent='悬浮/聚焦变量、术语或数字查看；点击固定；记录其余位置反选；Esc关闭';document.querySelector('.footer')?.prepend(hint);render(api.getState());
