import assert from 'node:assert/strict';import {writeFileSync,readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {buildModel,PRESETS,UNKNOWN} from './model.mjs';import {explain,leaves} from './provenance.mjs';
let queries=0,assertions=0,kinds=new Set(),phases=new Set();const eq=(a,b)=>{assert.deepEqual(a,b);assertions++;};
for(const preset of Object.keys(PRESETS)){const m=buildModel(preset);for(const f of m.frames){for(const [id,value]of Object.entries(f.snapshot)){kinds.add(m.ledger[id].obj);for(const leaf of leaves(value)){const q={objectId:id,elementPath:leaf.elementPath,step:f.step,phase:'observe'},x=explain(m,q);eq(x.result,leaf.value);assert(x.calculation.length&&x.calculation.every(s=>typeof s==='string'&&s.length));assert(x.sourceRef.file);assert(!x.calculation.some(s=>s.includes('NaN')));assert(x.producerStep<=f.step);assertions+=4;queries++;}}
for(const [phase,events,key]of[['read-before',f.reads,'value'],['write-before',f.writes,'before'],['write-after',f.writes,'after']])for(const event of events)for(const leaf of leaves(event[key])){const x=explain(m,{objectId:event.id,elementPath:leaf.elementPath,step:f.step,phase});eq(x.result,leaf.value);if(phase!=='write-after')assert(x.producerStep<f.step);else assert(x.producerStep<=f.step);assertions++;queries++;phases.add(phase);}
for(const event of f.writes)for(const leaf of leaves(event.after)){const x=explain(m,{objectId:event.id,elementPath:leaf.elementPath,step:f.step,phase:'history'});eq(x.result,leaf.value);eq(x.displayPhase,'write-after');queries++;}
}
for(const [k,v]of Object.entries(m.config))eq(explain(m,{objectId:'@config.'+k,step:0}).result,v);
const h=m.config.fp8?256:512,meta=m.config.fp8?96:m.config.cached?32:64;eq(m.config.hiddenBytes,h);eq(m.config.metadataBytes,meta);eq(m.config.tokenBytes,h+meta);eq(m.config.regionBytes,4*(h+meta));eq(m.config.bufferBytes,16*(h+meta));
for(let r=0;r<4;r++){const bydst=Array(4).fill(0);for(const t of m.tokens.filter(t=>t.r===r)){const dest=[...new Set(t.topk.filter(e=>e>=0).map(e=>Math.floor(e/2)))];dest.forEach(d=>bydst[d]++);for(let j=0;j<2;j++){if(t.slot[j]>=0){const earlier=m.tokens.filter(x=>x.r===r&&x.t<t.t).filter(x=>x.topk.some(e=>e>=0&&Math.floor(e/2)===Math.floor(t.topk[j]/2)));eq(t.slot[j],earlier.length);}}}if(!m.config.cached){const f=m.frames.find(f=>f.stage==='prefix');if(f)for(let d=0;d<4;d++){const x=explain(m,{objectId:`R${r}.rank_histogram_sum_view`,elementPath:[d],step:f.step,phase:'write-after'});eq(x.result,bydst[d]);eq(x.contributions.reduce((s,x)=>s+x.contribution,0),bydst[d]);}}
for(let e=0;e<2;e++){const n=m.tokens.filter(t=>t.topk.includes(r*2+e)).length;eq(m.expertCounts[r][e],n);eq(m.prefixExpert[r][e],(e?Math.ceil(m.expertCounts[r][0]/m.config.A)*m.config.A:0)+n);}}
}
const m=buildModel(),a=explain(m,{objectId:'R0.topk_idx[3]',elementPath:[0],step:0,phase:'initial'}),b=explain(m,{objectId:'R0.topk_idx[3]',elementPath:[1],step:0,phase:'initial'});eq(a.result,-1);assert(a.calculation.join('').includes('无专家'));eq(b.result,0);assert(b.calculation.join('').includes('floor(0÷2)=0'));const sum=explain(m,{objectId:'R0.rank_histogram_sum_view',elementPath:[0],step:5,phase:'write-after'});eq(sum.result,2);eq(sum.contributions.filter(x=>x.contribution===1).map(x=>x.token),[0,3]);
const hashes=Object.fromEntries(['model.mjs','provenance.mjs','numeric-ui.mjs','app.mjs','style.css'].map(f=>[f,createHash('sha256').update(readFileSync(f)).digest('hex')]));const result={hashes,queries,assertions,kinds:[...kinds],phases:[...phases],presets:Object.keys(PRESETS),note:'作者数值层覆盖与独立输入重算断言；独立review另存，不替代其结论'};writeFileSync('numeric-test-results.json',JSON.stringify(result,null,2));console.log(result);
