import {COMMIT,UNKNOWN,PADDING} from './model.mjs';
const D='deep_ep/include/deep_ep/impls/ep/dispatch.hpp',E='deep_ep/include/deep_ep/impls/ep/dispatch_copy_epilogue.hpp',L='deep_ep/include/deep_ep/layout/ep/token.hpp';
const align=(n,a)=>Math.ceil(n/a)*a,at=(v,p)=>p.reduce((x,k)=>x===UNKNOWN||x===PADDING?x:x===undefined||x===null||typeof x!=='object'?undefined:x[k],v);
const src=(file,line,fn)=>({commit:COMMIT,file,line,fn:fn|| (file===D?(line>=559?'dispatch_impl':'simt_persistent_worker'):file===E?'dispatch_copy_epilogue_impl':'TokenLayout'),url:`source.html?file=${encodeURIComponent(file)}&line=${line}`});
export function leaves(value,path=[]){if(value!==null&&typeof value==='object')return Object.entries(value).flatMap(([k,v])=>leaves(v,[...path,Array.isArray(value)?Number(k):k]));return [{elementPath:path,value}];}
export function tokenRanks(t){const valid=t.topk.filter(e=>e>=0);return [...new Set(valid.map(e=>Math.floor(e/2)))];}
export function rankContributions(m,r,dst,limit=m.config.T){return m.tokens.filter(t=>t.r===r&&t.t<limit).map(t=>({token:t.t,topk:t.topk,valid:t.topk.filter(e=>e>=0),mapped:t.topk.filter(e=>e>=0).map(e=>Math.floor(e/2)),deduplicated:tokenRanks(t),contribution:tokenRanks(t).includes(dst)?1:0}));}
const rankCount=(m,r,d)=>rankContributions(m,r,d).reduce((n,t)=>n+t.contribution,0);
const expertCount=(m,d,e)=>m.tokens.reduce((n,t)=>n+t.topk.filter(x=>x===d*2+e).length,0);
function rankMath(m,r,d,limit){const contributions=rankContributions(m,r,d,limit);return {contributions,operands:contributions.map(t=>({objectId:`R${r}.topk_idx[${t.token}]`,elementPath:[],value:t.topk,contribution:t.contribution})),calculation:[...(m.config.T===0?[`本轮T=0，所以来源R${r}有效token集合为空∅；没有有效expert映射或去重贡献，空集合求和=0。所有16 AIV仍以count0发布arrival1，不能省略同步。`]:[]),`每 Rank 专家数 E÷R = 8÷4 = 2。目的 Rank = floor(expert_id÷2)。`,...contributions.map(t=>`token ${t.token}: topk=${JSON.stringify(t.topk)}；过滤 -1 → ${JSON.stringify(t.valid)}；${t.valid.map(e=>`floor(${e}÷2)=${Math.floor(e/2)}`).join('，')||'无有效专家'}；目标去重 → {${t.deduplicated.map(x=>'R'+x).join(',')}}；对 R${d} 贡献 ${t.contribution}。`),`R${d} 计数 = 0${contributions.map(t=>' + '+t.contribution).join('')} = ${contributions.reduce((n,t)=>n+t.contribution,0)}。`],computed:contributions.reduce((n,t)=>n+t.contribution,0)};}
function selectMoment(m,q){const step=q.phase==='initial'?0:q.step,f=m.frames[step];if(!f)throw Error('未知步骤 '+step);const w=f.writes.find(x=>x.id===q.objectId),r=f.reads.find(x=>x.id===q.objectId);let phase=q.phase||'auto';if(phase==='auto'||phase==='history')phase=w?'write-after':r?'read-before':'observe';let cell;
 if(phase==='read-before'){if(!r)throw Error('本步没有读取 '+q.objectId);cell=r.value;}else if(phase==='write-before'){if(!w)throw Error('本步没有写入 '+q.objectId);cell=w.before;}else if(phase==='write-after'){if(!w)throw Error('本步没有写入 '+q.objectId);cell=w.after;}else cell=f.snapshot[q.objectId];
 const bound=phase==='write-before'||phase==='read-before'?step-1:step;let producer=-1;for(let i=0;i<=bound;i++)if(m.frames[i].writes.some(w=>w.id===q.objectId)&&fieldProduced(m,q.objectId,q.elementPath||[],m.frames[i]))producer=i;
 return {step,f,w,r,phase,result:at(cell,q.elementPath||[]),producerStep:producer,producer:producer<0?null:m.frames[producer]};}
function fieldProduced(m,id,path,f){const obj=m.ledger[id]?.obj,w=f.writes.find(w=>w.id===id);if(obj==='local_copy_dst_slot_idx'&&['slots','restore'].includes(f.stage)&&w?.after===-1)return false;if(['ub_expert_histogram','ub_rank_histogram'].includes(obj)&&f.stage==='histogram'&&path.length&&at(w?.before,path)===at(w?.after,path))return false;if(obj!=='signals'||path.length===0)return true;const field=path[0];return field==='metadata_ready'?f.title.startsWith('metadata_ready'):field==='local_copy_ready'?['slots','restore'].includes(f.stage):field==='doorbell'?f.stage==='issue':field==='payload'?f.stage==='receive':field==='arrival'?f.stage==='counts':false;}
export function explain(m,q){const p=q.elementPath||[],c=m.config;
 if(q.objectId.startsWith('@'))return explainMeta(m,{...q,elementPath:p});
 const l=m.ledger[q.objectId];if(!l)throw Error('解释未覆盖对象 '+q.objectId);const moment=selectMoment(m,{...q,elementPath:p}),{result,producerStep,producer,phase}=moment;
 if(result===undefined)throw Error('元素不存在 '+q.objectId+' '+JSON.stringify(p));
 const out={objectId:q.objectId,elementPath:p,step:moment.step,displayPhase:phase,history:q.phase==='history',producerStep,kind:'数值',unit:'元素',origin:producer?'本轮源码生产事件':'初始状态',operation:producer?'观察上次生产结果':'初始化',operands:[],calculation:[],result,sourceRef:src(D,112),contributions:[],arrayMeaning:l.shape.length?`逻辑 shape=${JSON.stringify(l.shape)}；元素路径 ${JSON.stringify(p)}。方括号表示数组元素列表，非数值区间。`:'标量字段'};
 const set=(operation,unit,calculation,sourceRef,extra={})=>Object.assign(out,{operation,unit,calculation:Array.isArray(calculation)?calculation:[calculation],sourceRef,...extra});
 const t=m.tokens.find(t=>t.r===l.rank&&t.t===Number(l.index)),r=l.rank,obj=l.obj;
 const cachedInitial=c.cached&&producerStep<0&&['topk_idx','dst_buffer_slot_idx','dst_gsge_idx','recv_src_metadata','psum_num_recv_tokens_per_rank','psum_num_recv_tokens_per_expert','num_unaligned_recv_tokens_per_expert'].includes(obj);
 if(cachedInitial)out.origin='前一次 fresh 调用的 handle 缓存继承；路由/容量/核数保持不变';
 if(Array.isArray(result)||result&&typeof result==='object'){set('对象/数组结构','元素',`这是 ${Array.isArray(result)?result.length+'个元素的数组':'包含命名字段的对象'}；每个叶元素可独立查询。不是区间；完整字段保留原顺序。`,src(L,13));return out;}
 if(result===UNKNOWN||result===PADDING||typeof result==='string'&&(result.includes('未定义')||result.includes('不发送')||result==='无SF分支')){
  out.kind='未定义/未写入';out.origin=result===UNKNOWN?(c.cached&&['ub_rank_histogram','ub_expert_histogram','rank_histogram_sum_view','expert_histogram_sum_view','epilogue_expert_counter'].includes(obj)?'cached跳过fresh统计分支；此教学对象没有本轮有效值':'torch::empty 或尚未发布的容量槽；没有本轮有效值'):result===PADDING?'32字节对齐的padding未被源码初始化':'可选/缓存分支未传输此字段';if(obj==='recv_buffer'&&result===UNKNOWN)out.origin='SymmetricMemory接收容量槽本轮尚未有效写入；须等drain与barrier再消费有效记录，空容量槽没有token';if(obj==='SQE'&&result===UNKNOWN)out.origin='Jetty SQ教学描述符尚未构造；该槽没有本轮有效SQE';if(obj==='epilogue_expert_counter'&&result===UNKNOWN&&!c.cached)out.origin='epilogue workspace尚未完成clear/barrier与前置核归约，前缀槽没有本轮有效值';set('不执行数值算术','状态',`${q.objectId}${JSON.stringify(p)} = ${result}。它不是数字0，不能作为有效载荷/计数读取。`,undefinedSource(m,l,p,result));return finish(out,m,q,moment);
 }
 if(obj==='x'){out.kind='人为载荷';out.origin='教学者选定的输入，非内核生成';const h=Number(p[0]);let calc;
  if(cachedInitial)out.origin+='；cached本轮允许更新hidden';
  if(m.tokens.every(t=>t.x.every(v=>v===0)))calc=`全零hidden预设把所有rank/token的向量人为设为0，x[${t.t},${h}]=0；有效0不是未写入。`;else if(t.gid===0)calc=`本预设仅将R0 token0（global_idx=0）的完整hidden向量人为设为0，其他token按下述生成公式取值。该元素x[0,${h}]=0；有效0不是未写入。`;
  else if(c.fp8)calc=`global_idx=r×M+t=${r}×4+${t.t}=${t.gid}；base=(global_idx+1) mod 4=(${t.gid}+1) mod 4=${(t.gid+1)%4}；hidden=${(t.gid+1)%4}+(${h} mod 2)=${result}，选择小整数以适合FP8并展示不同元素。`;
  else calc=`global_idx=${r}×4+${t.t}=${t.gid}；base=(global_idx+1)×2=(${t.gid}+1)×2=${(t.gid+1)*2}；hidden=base+(h mod 4)${c.cached?'+32（本轮人为更新）':''}=${(t.gid+1)*2}+(${h} mod 4)${c.cached?'+32':''}=${result}。`;
  set('人为选择输入','载荷元素',[calc,'此处只解释输入取值，不冒充内核计算或实测数据。'],src('deep_ep/buffers/ep.py',342,'EPBuffer.dispatch'));return finish(out,m,q,moment);
 }
 if(obj==='topk_idx'){out.kind='专家 ID / 哨兵';out.origin=c.cached?'handle继承上次人为路由':'教学者选定的非均匀路由输入';const j=Number(p[0]);set('人为路由选择','expert ID',result===-1?`topk_idx[${t.t}][${j}]=-1：该top-k lane无专家选择；过滤条件 expert_id≥0 不成立，不进入floor/原子计数。不是区间端点，也不是有效专家0。`:`topk_idx[${t.t}][${j}]=${result}：合法专家[0,8)中的有效expert。floor(${result}÷2)=${Math.floor(result/2)} 是目的rank，${result} mod 2=${result%2} 是local expert。输入选择用于展示${t.topk.filter(e=>e>=0).length===1?'一个有效专家与一个无选择lane':t.topk.filter(e=>e>=0).map(e=>Math.floor(e/2)).every(d=>d===Math.floor(result/2))?'同rank两个专家但只传一次hidden':'跨rank路径'}。`,src(D,177));return finish(out,m,q,moment);}
 if(obj==='topk_weights'){out.origin='人为选择的float32输入；cached可更新weights';set('人为输入','权重',`${c.cached?'cached本轮选择[0.25,0.75]':'fresh选择[0.6,0.4]'}，lane ${p[0]} 的独立权重=${result}。${c.cached?'0.25+0.75=1':'0.6+0.4=1'}只是输入设计；dispatch原样复制对应expert权重，不将hidden乘以此数。`,src(D,741));return finish(out,m,q,moment);}
 if(obj==='sf'){out.origin='人为选择的SF pack原始位模式';set('人为位模式输入','int16 pack位模式',`SF[${p[0]}]=0x3c00+${p[0]}；0x3c00=3×4096+12×256=15360；15360+${p[0]}=${result}（0x${Number(result).toString(16)}）。仅按sf_pack_t=int16搬运，未解码scale。`,src(D,701));return finish(out,m,q,moment);}
 if(producerStep<0&&!cachedInitial&&['ub_rank_histogram','ub_expert_histogram','rank_histogram_sum_view','expert_histogram_sum_view','local_rank_histogram','local_copy_dst_slot_idx','signals'].includes(obj)){
  out.origin=obj.endsWith('_sum_view')?'教学聚合视图初始化，非真实GM分配':'源码初始化 / workspace初始清零';set('源码/教学初始化','状态或计数',result===-1?`${obj} 初始 -1 表示尚无本机复制目标槽，不是无expert。`:`初始值 ${result}：${obj==='signals'?'ready=0尚未发布；doorbell未提交':obj==='local_rank_histogram'?'完整信号0=未到达/可复用，不能当作arrival1的空计数':'计数器尚未计入任何token'}。没有加法贡献事件。`,obj.endsWith('_sum_view')||obj==='local_rank_histogram'?ledgerSource(l):obj==='signals'?(p[0]==='metadata_ready'?src(D,663):p[0]==='local_copy_ready'?src(D,662):ledgerSource(l)):src(D,obj==='local_copy_dst_slot_idx'?126:obj==='ub_rank_histogram'?123:121));return finish(out,m,q,moment);
 }
 if(obj==='rank_histogram_sum_view'||obj==='ub_rank_histogram'||obj==='local_rank_histogram'&&p[0]!=='arrival'){
  if(obj==='local_rank_histogram'&&p.length===0){set('清信号','同步状态',`读取arrival2前缀后把整个GM信号写0；0表示为下次调用清理，不代表旧前缀/载荷被清零。`,src(D,253));return finish(out,m,q,moment);}
  let d=Number(obj==='local_rank_histogram'?p[1]:p[0]),core=Number(l.index),limit=c.T;
  if(obj==='ub_rank_histogram'||obj==='local_rank_histogram'){if(producer?.stage==='prefix')limit=Math.min(core,c.T);else limit=Math.min(core+1,c.T);}
  const x=rankMath(m,r,d,limit);if(obj!=='rank_histogram_sum_view'&&producer?.stage!=='prefix'){
   const one=x.contributions.filter(x=>x.token===core);x.contributions=one;x.operands=x.operands.filter(z=>z.objectId===`R${r}.topk_idx[${core}]`);x.calculation=[`AIV ${core} 名义负责 token 区间 [${core},${core+1})；与有效区间[0,${c.T})交集${core>=c.T?'为空∅':`为[${core},${core+1})`}。${core>=c.T?'空范围，仍发布arrival1/count0。':''}`,...rankMath(m,r,d,Math.min(core+1,c.T)).calculation.filter(s=>s.startsWith(`token ${core}:`)),`本核计数 = ${one.map(x=>x.contribution).join(' + ')||'0'} = ${result}。`];}
  set(obj==='rank_histogram_sum_view'?'跨核去重计数求和':producer?.stage==='prefix'?'排他式跨核前缀':'本核去重计数','token条数',x.calculation,src(D,obj==='rank_histogram_sum_view'?242:producer?.stage==='prefix'?244:186),x);out.computed=obj==='rank_histogram_sum_view'||producer?.stage==='prefix'?x.contributions.reduce((n,x)=>n+x.contribution,0):x.contributions.reduce((n,x)=>n+x.contribution,0);if(obj==='rank_histogram_sum_view'){out.origin='跨核计数教学聚合；不是独立真实GM数组';out.calculation.push('sum_view把各AIV本地计数聚合展示；真实rank_histogram在prefix后覆盖为每核排他前缀。');}return finish(out,m,q,moment);
 }
 if(obj==='local_rank_histogram'&&p[0]==='arrival'){set('发布同步状态','arrival阶段码',result===1?'计数（含空核count0）写入GM时带1×kReductionIdentity；高8位到达状态=1，消费者等待1后才读count。':'计数已转换为排他前缀，状态=2×kReductionIdentity；等待2后可读取前缀。随后清整个信号0。',src(D,result===1?221:244));return finish(out,m,q,moment);}
 if(obj==='expert_histogram_sum_view'||obj==='ub_expert_histogram'){
  const e=Number(p[0]),core=Number(l.index),max=obj==='ub_expert_histogram'?core+1:producer?.writes.reduce((mx,w)=>m.ledger[w.id]?.obj==='ub_expert_histogram'?Math.max(mx,Number(m.ledger[w.id].index)+1):mx,0)||c.T;
  if(obj==='expert_histogram_sum_view')out.origin='跨核expert命中计数教学聚合；不是独立真实GM数组';const ts=m.tokens.filter(t=>t.r===r&&t.t<max&&(obj!=='ub_expert_histogram'||t.t===core));const contributions=ts.map(t=>({token:t.t,topk:t.topk,contribution:t.topk.filter(x=>x===e).length}));set('每个有效expert计数；不按rank去重','expert命中条数',[...contributions.map(x=>`token ${x.token}: topk=${JSON.stringify(x.topk)} → expert ${e} 命中 ${x.contribution}。`),`0${contributions.map(x=>' + '+x.contribution).join('')} = ${result}。${obj.endsWith('_sum_view')?'跨核教学聚合，非一个真实GM数组。':''}`],src(D,179),{contributions});return finish(out,m,q,moment);
 }
 if(obj==='num_unaligned_recv_tokens_per_expert'||obj==='psum_num_recv_tokens_per_expert'){
  const e=Number(p[0]),counts=[expertCount(m,r,0),expertCount(m,r,1)],calc=[];for(let le=0;le<=e;le++){const matches=m.tokens.filter(t=>t.topk.includes(r*2+le));calc.push(`expert ${r*2+le} 的有效来源 ${matches.map(t=>`R${t.r}/token${t.t}`).join(', ')||'无'} → raw_count=${counts[le]}。`);}
  if(obj==='psum_num_recv_tokens_per_expert')calc.push(...counts.slice(0,e).map(n=>`align(${n},${c.A})=ceil(${n}÷${c.A})×${c.A}=${align(n,c.A)}。`),`expert_end[${e}]=${counts.slice(0,e).map(n=>align(n,c.A)).join(' + ')||'0'} + 当前raw_count ${counts[e]} = ${result}。不是纯raw前缀，也不是纯aligned总和。`);
  else calc.push(`raw_count[${e}]=${counts[e]}，不包含padding。`);set(obj.startsWith('psum')?'前置aligned容量 + 当前raw count':'跨rank专家命中归约','token条数',calc,src(D,obj.startsWith('psum')?519:482),{operands:counts.map((v,i)=>({objectId:`expert ${r*2+i} raw count`,value:v}))});return finish(out,m,q,moment);
 }
 if(obj==='psum_num_recv_tokens_per_rank'){const i=Number(p[0]),ns=Array.from({length:4},(_,s)=>rankCount(m,s,r));set('包含式来源rank前缀','接收记录条数',[...ns.slice(0,i+1).flatMap((n,s)=>[`来源R${s} → 目的R${r}，${c.cached?'上次fresh':'本轮fresh'}逐token贡献：`,...rankMath(m,s,r,c.T).calculation]),`${ns.slice(0,i+1).join(' + ')} = ${result}。包含来源rank ${i} 自己；来源分区物理容量仍各有M=4槽。`],src(D,538),{operands:ns.slice(0,i+1).map((value,s)=>({objectId:`R${s}.rank_histogram_sum_view`,elementPath:[r],value}))});return finish(out,m,q,moment);}
 if(['dst_buffer_slot_idx','dst_gsge_idx','local_copy_dst_slot_idx'].includes(obj)){
  const j=obj==='local_copy_dst_slot_idx'?t.topk.findIndex(e=>e>=0&&Math.floor(e/2)===r):Number(p[0]),e=t.topk[j],d=e>=0?Math.floor(e/2):-1;
  if(result===-1){const duplicate=e>=0&&t.topk.slice(0,j).some(x=>x>=0&&Math.floor(x/2)===d);set('哨兵分支，不分配新条目',obj==='dst_gsge_idx'?'SGE pair索引':'接收槽索引',obj==='local_copy_dst_slot_idx'?`token ${t.t} 没有本机rank专家，local_copy_dst_slot_idx=-1，跳过本机hidden/metadata复制。`:obj==='dst_gsge_idx'&&d===r?'本机路径不使用远端SGE，因此dst_gsge_idx=-1；本机槽仍有效。':duplicate?`topk lane ${j} 的目的R${d}与前面lane相同，rank去重后此lane=-1；已保留另一lane副本。`:`expert=${e} 无有效目的，${obj}=-1；表示无槽/SGE，不是专家哨兵本身。`,src(D,281));}
  else if(obj==='dst_gsge_idx'){const peers=tokenRanks(t).filter(x=>x!==r).sort((a,b)=>(a-r+4)%4-(b-r+4)%4),base=peers.indexOf(d);set('所选合法逻辑SQE线性化','SGE pair索引',[`目的peer按教学循环顺序 ${peers.map(x=>`R${x}（(${x}-${r}+4) mod 4=${(x-r+4)%4}）`).join(', ')}。`,`目的R${d}的lsqe_base=${base}；每核只有1 token，所以sgep_idx=原子返回旧值0。`,`global_sgep_idx=lsqe_base×6+sgep_idx=${base}×6+0=${result}。这是一种合法取号顺序，非硬件确定排序。`],src(D,274));}
  else{const x=rankMath(m,r,d,t.t),pre=x.computed;set('排他前缀 + 原子旧值','接收槽索引',[...x.calculation,`本AIV只有token ${t.t}，rank_histogram原子取号返回0（0→1）。dst_slot_idx=${pre}+0=${result}；slot相对于目的R${d}的来源R${r}分区。`],src(D,d===r?277:272),{operands:x.operands,contributions:x.contributions});}
  return finish(out,m,q,moment);
 }
 if(obj==='metadata_send_buffer'){
  const field=p[0],j=p[1];if(['topk','weights','sf'].includes(field)){const from=field==='topk'?'topk_idx':field==='weights'?'topk_weights':'sf';set('GM→UB打包→GM原样复制',field==='sf'?'int16 pack位模式':field==='topk'?'expert ID':'权重',`从 R${r}.${from}[${t.t}][${j}]=${result} 原样搬到metadata_send_buffer对应字段；${result===0?'有效0仍是写入。':''}复制不进行加减乘除。alignment padding另标未定义。`,src(D,786),{operands:[{objectId:`R${r}.${from}[${t.t}]`,elementPath:[j],value:result}]});}
  else if(field==='src_global_idx')set('生成来源编号','全局token索引',`src_token_global_idx=rank×M+token_idx=${r}×4+${t.t}=${result}；乘的是容量M，不是本轮T。`,src(D,779));else if(field==='padding')throw Error('padding应进入未定义分支');else set('可选字段未提供','状态',`${field}=${result}，该分支没有有效输入或没有传输；不伪造数值。`,src(D,727));return finish(out,m,q,moment);
 }
 if(obj==='recv_buffer'){
  const [source,slot]=String(l.index).split(',').map(Number),rec=m.recvPlan[r].find(x=>x.r===source&&x.slot===slot);if(!rec)throw Error('不存在的有效recv record');const field=p[0];
  if(field==='hidden'||field==='metadata'){const from=field==='hidden'?`R${rec.r}.x[${rec.t}]`:`R${rec.r}.metadata_send_buffer[${rec.t}]`,path=p.slice(1);set(rec.r===r?'本机MTE/SIMT复制':'URMA WRITE复制',field==='hidden'?'载荷元素':'metadata字段',[`来源=${from}${JSON.stringify(path)}，值=${JSON.stringify(result)}，原样写入目的R${r}.recv_buffer[${source},${slot}]。`,`物理字节偏移=(src_rank×M+slot)×record_bytes=(${source}×4+${slot})×${c.tokenBytes}=${(source*4+slot)*c.tokenBytes}B。`,`这是新副本；${result===0?'零值复制也实际写0，不是未写入。':''}不制造虚假的算术载荷。`],src(D,rec.r===r?(field==='hidden'?835:444):422),{operands:[{objectId:from,elementPath:path,value:result}]});}
  else set('接收record身份/完成状态','状态',`${field}=${result} 标明 ${rec.r===r?'本机复制':'远端WRITE'}来源与完成条件；payload就绪依赖epilogue drain/barrier，计数先到不足以推导payload就绪。`,src(E,200));return finish(out,m,q,moment);
 }
 if(['recv_x','recv_topk_weights','recv_sf'].includes(obj)){
  const slot=Number(l.index),rec=m.outputPlan[r].find(x=>x.slots.includes(slot));if(!rec){set('显式padding清零',obj==='recv_sf'?'pack位模式':'载荷/权重',[`槽${slot}是expert对齐padding，没有来源token或src_metadata。`,`do_zero_padding=True，零缓冲或WriteGmByPassDCache将此元素写0。不是路由贡献，不由有效token算出。`],src(E,obj==='recv_x'?567:obj==='recv_sf'?588:580));}
  else{const j=rec.slots.indexOf(slot),field=obj==='recv_x'?'hidden':obj==='recv_sf'?'metadata.sf':'metadata.weights',path=obj==='recv_x'?['hidden',...p]:obj==='recv_sf'?['metadata','sf',...p]:['metadata','weights',j];set('按local expert展开，原样复制',obj==='recv_x'?'载荷元素':obj==='recv_sf'?'int16 pack位模式':'权重',[`接收rank去重token来自R${rec.r}/token${rec.t}，local expert ${rec.topk[j]}匹配top-k lane ${j}，输出槽=${slot}。`,`从 R${r}.recv_buffer[${rec.r},${rec.slot}] 的${field}${JSON.stringify(p)}=${result} 原样写到 ${q.objectId}${JSON.stringify(p)}。`,`hidden不乘权重；SF只复制位模式；相同值/有效0也是一次实际写入。`],src(E,obj==='recv_x'?492:obj==='recv_sf'?499:507),{operands:[{objectId:`R${r}.recv_buffer[${rec.r},${rec.slot}]`,elementPath:path,value:result}]});}return finish(out,m,q,moment);
 }
 if(obj==='recv_src_metadata'){
  const pos=Number(l.index),rec=m.recvPlan[r][pos],j=Number(p[0]);if(j<2){const e=rec.topk[j],le=e-r*2;if(le<0||le>=2)set('非本地专家槽哨兵','expanded槽索引',`topk[${j}]=${e}，local_expert=${e}-${r}×2=${le}不在[0,2)，因此此metadata元素=-1；不在本rank展开。`,src(E,479));else{const rawPrev=le===0?0:expertCount(m,r,0),start=align(rawPrev,c.A),before=m.recvPlan[r].slice(0,pos).filter(x=>x.topk.includes(e));set('对齐起点 + 前置命中数','expanded槽索引',[`expert ${e} 的起点=${le===0?'0':`align(${rawPrev},${c.A})=ceil(${rawPrev}÷${c.A})×${c.A}=${start}`}。`,`接收流位置[0,${pos})中命中expert ${e}的记录=${before.map(x=>`R${x.r}/token${x.t}`).join(', ')||'无'}，数量=${before.length}。`,`dst_slot_idx=expert_start+前置核命中=${start}+${before.length}=${result}；本核next_slot随后${result}→${result+1}。`],src(E,484),{operands:[{objectId:'expert_start',value:start},{objectId:'前置接收流命中',value:before.length}]});}}
  else if(j===2)set('来源global_idx复制','全局token索引',`来源global_idx=src_rank×M+token_idx=${rec.r}×4+${rec.t}=${result}，从接收metadata原样搬到此字段。`,src(E,520));else if(j===3){const matches=rec.topk.map((e,j)=>e>=r*2&&e<r*2+2?j:-1).filter(j=>j>=0);set('取最后一个本地匹配lane','top-k lane索引',`本rank R${r}匹配的top-k lanes=${JSON.stringify(matches)}；每次匹配覆盖master，最后j=${matches.at(-1)??-1}，结果=${result}；不是第一个lane。`,src(E,486));}else throw Error('未知metadata元素');return finish(out,m,q,moment);
 }
 if(obj==='epilogue_expert_counter'){
  const core=Number(p[0]),le=Number(p[1]),e=r*2+le,part=m.recvPlan[r].slice(0,core);set('前置AIV原始命中排他前缀','token条数',[`ceil(num_recv_tokens÷16)=ceil(${m.recvPlan[r].length}÷16)=${Math.ceil(m.recvPlan[r].length/16)}；本小例每活跃AIV≤1记录。`,`前置核[0,${core})对应接收流前${core}条；expert ${e} 的逐条贡献=${part.map(x=>x.topk.includes(e)?1:0).join(', ')||'空'}。`,`0${part.map(x=>' + '+(x.topk.includes(e)?1:0)).join('')} = ${result}。这里尚未加aligned expert_start；initialize_dst_slot_idx在下一操作加起点。`],src(E,404));return finish(out,m,q,moment);
 }
 if(obj==='SQE')return finish(explainSQE(m,out,l,p,result),m,q,moment);
 if(obj==='signals'){out.kind='同步/提交状态';set('条件发布 / 状态转移','状态码',p[0]==='metadata_ready'?`metadata_ready=${result}：${result===1?'MTE3 metadata flush完成后MTE2→S汇合，发布可供SIMT读取':'metadata尚未发布；不是metadata字节值'}。`:p[0]==='local_copy_ready'?`local_copy_ready=${result}：${result===1?'SIMT槽位计算完成后发布；scalar等待1才读local slot':'槽位尚未发布；不是payload完成标志'}。`:`${p[0]}=${result}：本模型按rank聚合真实各AIV条件；已提交doorbell不等于URMA完成，counts就绪不等于hidden就绪。`,p[0]==='payload'?src(E,200):src(D,p[0]==='metadata_ready'?801:p[0]==='local_copy_ready'?298:p[0]==='arrival'?519:857));return finish(out,m,q,moment);}
 throw Error('没有针对字段的解释处理器：'+obj+' '+JSON.stringify(p));
}
function finish(out,m,q,moment){copyIdentity(out,m,q);addDerived(out,m,q,moment);for(const operand of out.operands){if(operand.objectId in m.ledger&&operand.scope!=='previous-fresh'){const f=moment.producer||m.frames[0],read=f.reads.find(r=>r.id===operand.objectId),snapshot=m.frames[Math.max(0,moment.producerStep-1)].snapshot;operand.value=at(read?read.value:snapshot[operand.objectId],operand.elementPath||[]);operand.phase=read?'read-before':'source-before-producer';operand.step=moment.producerStep<0?0:moment.producerStep;}}if(out.origin.includes('人为')||out.origin.includes('教学者')){out.implementationRef=out.sourceRef;out.sourceRef={commit:COMMIT,file:'animation/model.mjs',line:m.ledger[q.objectId]?.obj==='topk_idx'?5:m.ledger[q.objectId]?.obj==='x'?14:15,fn:'buildModel（教学者选择输入）',url:'model.mjs',kind:'teaching-input'};}const w=moment.w,path=q.elementPath||[];if(w&&['ub_expert_histogram','ub_rank_histogram','local_copy_dst_slot_idx'].includes(m.ledger[q.objectId]?.obj)&&!fieldProduced(m,q.objectId,path,moment.f)){out.operation='保留初始化；本步未对该元素写入';out.calculation.push(m.ledger[q.objectId].obj==='local_copy_dst_slot_idx'?'本token没有本地目的rank，slots/restore不进入local赋值分支；保留初始化-1，模型聚合记录不代表又写了一次-1。':'该UB bucket本步无匹配贡献，没有原子写操作；沿用初始化0，模型整数组统计记录不代表真实同值写0。');}out.before=w?at(w.before,path):undefined;out.after=w?at(w.after,path):undefined;if(q.phase==='write-before'||moment.phase==='read-before'){out.calculation.push(`本步 ${moment.phase==='read-before'?'读取前':'写入前'} 值=${JSON.stringify(out.result)}；生产事件仍是${out.producerStep<0?'初始状态':'步骤'+out.producerStep}，不能使用本步写后值。`);}if(m.ledger[q.objectId]?.obj==='signals'&&w&&!fieldProduced(m,q.objectId,path,moment.f)){out.operation='保留字段；非本步写操作';out.calculation.push('本帧只替换聚合对象其他字段；此字段沿用真正生产步骤，不伪称同值写入。');}if(w)out.transition=`${JSON.stringify(out.before)} → ${JSON.stringify(out.after)}`;if(m.config.cached&&moment.producerStep<0&&['dst_buffer_slot_idx','dst_gsge_idx','recv_src_metadata','psum_num_recv_tokens_per_rank','psum_num_recv_tokens_per_expert','num_unaligned_recv_tokens_per_expert'].includes(m.ledger[q.objectId].obj)){out.operation='缓存继承；复用上次fresh布局';out.calculation.unshift('以下推导是上次fresh生产该缓存的依据，本轮不重新执行路由/count/slot计算。');out.sourceRef=['dst_buffer_slot_idx','dst_gsge_idx'].includes(m.ledger[q.objectId].obj)?src(D,140):src('csrc/buffers/ep.hpp',m.ledger[q.objectId].obj==='recv_src_metadata'?340:m.ledger[q.objectId].obj==='psum_num_recv_tokens_per_rank'?205:m.ledger[q.objectId].obj==='psum_num_recv_tokens_per_expert'?208:211,'EPBuffer::dispatch');}out.actor=out.producerStep>=0?m.frames[out.producerStep].actors.join('；'):'教学输入 / 源码初始化';return out;}
function explainSQE(m,out,l,p,value){const c=m.config,t=m.tokens.find(t=>t.r===l.rank&&t.t===Number(l.index)),peer=tokenRanks(t).filter(d=>d!==l.rank).sort((a,b)=>(a-l.rank+4)%4-(b-l.rank+4)%4),i=Number(p[0]),d=peer[i],j=t.topk.findIndex(e=>e>=0&&Math.floor(e/2)===d),slot=t.slot[j],field=p[1];Object.assign(out,{unit:'描述符字段',sourceRef:src(D,403),operation:'构造SQE/SGE字段',kind:'URMA命令字段'});
 const units={logicalSQE:'逻辑SQE索引（教学线性化）',physicalSQE:'物理SQE索引',dst_rank:'rank索引',dst_slot:'来源rank分区槽索引',remote_offset:'字节偏移',num_sges:'SGE个数',validWQEBBs:'64B有效块个数',reservedWQEBBs:'64B预留块个数',finalFlags:'最后物理SQE的布尔条件'};const lines={logicalSQE:205,physicalSQE:340,dst_rank:351,dst_slot:352,remote_offset:402,num_sges:372,validWQEBBs:373,reservedWQEBBs:24,finalFlags:395};if(field!=='SGEs'){out.unit=units[field];out.sourceRef=src(D,lines[field],field==='reservedWQEBBs'?'kNumWQEBBsPerSQESlot':undefined);}const msg={logicalSQE:`前面有${i}个remote peer SQE，本教学线性化的logicalSQE=${i}。`,physicalSQE:`物理原子取号采用同一合法线性化，physicalSQE=${i}；不声称硬件固定此顺序。`,dst_rank:`expert=${t.topk[j]} → floor(${t.topk[j]}÷2)=${d}。`,dst_slot:`本源rank前token目标R${d}计数=${rankCountBefore(m,t,d)}，本核原子旧值0；${rankCountBefore(m,t,d)}+0=${slot}。`,remote_offset:`remote byte offset=(src_rank×M+dst_slot)×token_bytes=(${l.rank}×4+${slot})×${c.tokenBytes}=${value}B。`,num_sges:'一个有效rank副本有hidden与metadata两个SGE；num_sges=1×2=2。',validWQEBBs:'48B header + 2×16B SGE=80B；ceil(80÷64)=2个有效WQEBB。',reservedWQEBBs:'源码每SQE固定预留4×64B=256B；本例2个有效WQEBB，其余写NOP。',finalFlags:`physicalSQE ${i}${i===peer.length-1?'是':'不是'}本核最后SQE（${peer.length}-1=${peer.length-1}），finalFlags=${value}。这是本教学字段的布尔值，不是packed flags字。true请求strong order/fence/CQE；条件由physicalSQE是否最后决定。不表示提交即完成。`};
 if(field==='SGEs'){const component=Number(p[2]),leaf=p[3];out.unit=leaf==='bytes'?'字节':'符号GM地址';out.sourceRef=src(D,component===0?(leaf==='bytes'?407:409):(leaf==='bytes'?411:413));out.calculation=[leaf==='bytes'?component===0?`hidden_bytes=H×element_size=256×${c.fp8?1:2}=${c.hiddenBytes}B。`:`metadata_bytes=${c.sfPacks?'align(8×2,32)=32 + ':''}align(${c.cached?'K×4=2×4=8':'align(K×8,32)+K×4+4=32+8+4=44'},32)=${c.metadataBytes}B。`:`${component===0?'x':'metadata_send_buffer'}源地址=基址+token_idx×record_stride=${component===0?'x':'metadata_send_buffer'} + ${t.t}×${component===0?c.hiddenBytes:c.metadataBytes}；字节偏移=${t.t*(component===0?c.hiddenBytes:c.metadataBytes)}，基址符号包含源rank身份R${l.rank}。`];}
 else{if(!(field in msg))throw Error('未覆盖SQE field '+field);out.calculation=[msg[field]];}return out;}
const rankCountBefore=(m,t,d)=>rankContributions(m,t.r,d,t.t).reduce((n,x)=>n+x.contribution,0);
function explainMeta(m,q){const c=m.config,p=q.elementPath||[],key=q.objectId.slice(1),parts=key.split('.');let result,calculation,unit='教学参数',sourceRef=src(L,13),origin='人为选择的教学配置',operation='参数/索引语义';
 if(parts[0]==='config'){const k=parts[1];if(!(k in c))throw Error('未知config '+k);result=c[k];const text={R:'选择4个真实rank，展示多来源、多目的及空peer。',E:'选择8个专家；E÷R=8÷4=2专家/rank。',K:'每token有2个top-k数组元素；不是区间。有效expert须互异。',H:'hidden维度256个载荷元素；不是token数。',M:'每rank最大容量4条；用于source global编号及接收分区。',T:`本轮每rank ${c.T}条token；T≤M=4；空预设T=0。`,C:'launch16个AIV/rank，满足host最低16；ceil(M/C)=ceil(4/16)=1输入token/AIV。',A:`expert行对齐量${c.A}，是2的幂；padding按各expert独立补齐。`,hiddenBytes:`H×element_size=256×${c.fp8?1:2}=${c.hiddenBytes}字节。`,sfPacks:`人为选择${c.sfPacks}个int16 SF packs；${c.sfPacks===0?'BF16无SF分支':'FP8示例仅搬位模式'}。`,sfBytes:`SF字节=${c.sfPacks}×sizeof(int16)=${c.sfPacks}×2=${c.sfBytes}。`,metadataBytes:`${c.sfPacks?`SF区 align(${c.sfBytes},32)=32；`:''}metadata有效字段=${c.cached?'weights K×4=8':'topk align(K×8,32)=32；weights K×4=8；global_idx4；合计44'}；最终align(${c.cached?8:44},32)=${c.cached?32:64}；总metadata=${c.metadataBytes}B。`,tokenBytes:`record=hidden_bytes+metadata_bytes=${c.hiddenBytes}+${c.metadataBytes}=${c.tokenBytes}B。`,regionBytes:`来源rank分区=M×record=4×${c.tokenBytes}=${c.regionBytes}B。`,bufferBytes:`目的rank缓冲区容量=R×region=4×${c.regionBytes}=${c.bufferBytes}B，16槽不等于16个有效token。`,cached:'cached必须复用相同路由handle；不重算count/slot，只更新hidden、可选weights/SF。',fp8:'FP8时hidden元素1B，SF为int16 packs；不解码scale。',weights:'是否提供topk_weights；false时预留metadata权重区域未定义，不写recv_topk_weights。',zeroPadding:'是否明确写0到expert padding；false时未定义，不能当作有效零token。'};calculation=[text[k]];if(!text[k])throw Error('无config解释 '+k);unit=k.includes('Bytes')?'字节':typeof result==='boolean'?'分支条件':'参数计数';}
 else if(parts[0]==='control'){if(parts[1]!=='speed')throw Error('未知control数值');result=q.value;unit='毫秒/教学步';origin='人为选择的教学播放速度';calculation=[`播放间隔=${result}毫秒÷1000=${result/1000}秒/步；只控制教学播放器，不代表NPU时延。`];}
 else if(parts[0]==='dtype'){const l=m.ledger[q.object];if(!l)throw Error('未知dtype对象');result=l.dtype;unit='数据类型';calculation=[`${q.object} 使用 ${l.dtype}。${l.dtype==='bfloat16'?'BF16每载荷元素2B。':l.dtype==='float8_e4m3fn'?'FP8每载荷元素1B。':l.dtype.includes('int16')?'int16 SF pack为2B原始位模式，不解码scale。':l.dtype==='int64'?'每expert ID为8B；-1是无选择哨兵。':l.dtype==='int32'?'每计数/槽/metadata字段4B；具体哨兵由字段决定。':l.dtype==='float32'?'每权重为4B；dispatch只复制不乘hidden。':l.dtype==='WQEBB'?'64B为一个WQEBB；每SQE预留4个。':l.dtype==='uint8'?'原始连续字节buffer；具体record字段有各自dtype。':'教学聚合状态，非实际C++ struct。'}`];}
 else if(parts[0]==='shape'||parts[0]==='bytes'){const l=m.ledger[q.object];if(!l)throw Error('未知ledger meta');if(parts[0]==='shape'){result=l.shape[Number(q.index)];calculation=[`${q.object} 的逻辑shape=${JSON.stringify(l.shape)}，维${q.index}长度=${result}；属于元素数量，非区间端点。容量可以包含未写入槽。`];unit='维长度';}else{result=l.bytes;calculation=[`${q.object} 分配/逻辑记录容量=${result}字节；dtype=${l.dtype}，shape=${JSON.stringify(l.shape)}。${l.obj.endsWith('_sum_view')?'跨核教学聚合视图；容量是等效数组大小，没有真实GM分配。':l.obj==='x'||l.obj==='recv_x'?`256×${c.fp8?1:2}=${result}B。`:l.obj==='metadata_send_buffer'?`metadata布局由align的topk/weights/global_idx/SF区域构成，总${c.metadataBytes}B。`:l.obj==='recv_buffer'?`${c.hiddenBytes}+${c.metadataBytes}=${result}B。`:l.obj==='SQE'?'每SQE固定4×64=256B。':['int32','int64','float32','sf_pack_t=int16'].includes(l.dtype)?`每${l.dtype}=${l.dtype==='int64'?8:l.dtype==='sf_pack_t=int16'?2:4}B；元素容量 ${l.shape.reduce((n,k)=>n*k,1)}×${l.dtype==='int64'?8:l.dtype==='sf_pack_t=int16'?2:4}=${result}B。`:l.obj.endsWith('_sum_view')?'跨核教学聚合视图，容量字段是等效数组大小；没有真实GM分配。':l.obj==='signals'?'0字节是教学聚合容器占用记号，非真实UB flags不存在。':'未知dtype/容量定义（应显式检查对象说明）。'}`];unit='字节';}}
 else if(parts[0]==='index'){result=q.value;unit='索引';origin='对象寻址/界面选择';const kind=parts[1];const text={rank:`rank索引${result}在[0,4)，负责global experts ${result*2}、${result*2+1}。`,token:c.T===0?`token选择器值${result}只是空输入的界面占位；本预设有效区间[0,0)为空，没有实际token，不能据此读x或topk。`:`源token索引${result}在[0,T)；该token的输入AIV=floor(token/ceil(M/C))=floor(${result}/1)=${result}。`,hidden:`hidden元素索引${result}在[0,256)，包含0…255；不是整个token。`,expert:`global expert ID=${result}；floor(${result}/2)=${Math.floor(result/2)} rank，${result} mod 2=${result%2} local expert。`,slot:`槽索引${result}；具体生产/寻址依据请查看同对象数据字段，槽编号本身不是载荷。`,lane:`top-k lane=${result}，在[0,2)中选择数组第${result}个元素。`,length:`数组实际长度=${result}，属于元素个数；不是数值区间。`,aiv:`AIV核索引${result}在[0,16)；ceil(M/C)=ceil(4/16)=1，核${result}名义处理区间[${result},${result+1})，与有效[0,T)取交集；${result>=c.T?'本预设交集为空∅，仍参与count0同步':'该核有一条有效token'}。`,step:`教学步骤${result}，不是时延或实机全局同步时刻。`};if(!text[kind])throw Error('未知索引种类 '+kind);calculation=[text[kind]];}
 else if(parts[0]==='metric'){result=q.value;unit=q.unit||'条数';origin='从原始教学输入推导';const k=parts[1],r=q.rank,e=q.expert;
  if(k==='expertCount'){const hits=m.tokens.filter(t=>t.topk.includes(r*2+e));calculation=[`global expert=${r}×2+${e}=${r*2+e}；有效来源 ${hits.map(t=>`R${t.r}/token${t.t}`).join(', ')||'无'}；每次匹配贡献1，不按目的rank合并expert。总计=${hits.length}。`];}
  else if(k==='expertStart'){const n=e===0?0:expertCount(m,r,0);calculation=[e===0?'第一个local expert起点=0。':`前local expert有效末端=${n}；align(${n},${c.A})=ceil(${n}÷${c.A})×${c.A}=${align(n,c.A)}，作为当前expert起点；补齐${align(n,c.A)}-${n}=${align(n,c.A)-n}行。`];}
  else if(k==='recvCount')calculation=[`目的R${r}按来源rank计数=${[0,1,2,3].map(s=>rankCount(m,s,r)).join(' + ')}=${m.recvPlan[r].length}；每token每目的rank只1条。`];
  else if(k==='expandedCount')calculation=[`两个local expert raw=[${expertCount(m,r,0)},${expertCount(m,r,1)}]；容量=align(raw0,A)+align(raw1,A)=${align(expertCount(m,r,0),c.A)}+${align(expertCount(m,r,1),c.A)}=${m.expanded[r]}。`];
  else if(k==='sourceExpertHits'){const ts=m.tokens.filter(t=>t.r===r);calculation=[...ts.map(t=>`token${t.t}: ${JSON.stringify(t.topk)}过滤-1 → ${t.topk.filter(e=>e>=0).length}次expert命中`),`加总=${ts.map(t=>t.topk.filter(e=>e>=0).length).join('+')||'0'}=${result}。`];}
  else if(k==='sqeCount'||k==='sgeCount'){const ts=m.tokens.find(t=>t.key===q.tokenKey),n=tokenRanks(ts).filter(d=>d!==ts.r).length;calculation=[`token ${ts.t}有效目的去重=${JSON.stringify(tokenRanks(ts))}；去掉本机R${ts.r}后remote peers=${n}。每peer本例只有1 pair/SQE，因此${k==='sqeCount'?`SQE数量=${n}`:`SGE数量=${n}×2=${n*2}`}。`];}
  else if(k==='globalIdx'){calculation=[`来源编号=src_rank×M+token_idx=${q.sourceRank}×4+${q.token}=${result}。`];unit='全局token索引';}
  else if(k==='capacitySlots')calculation=['R×M=4×4=16接收容量槽；各来源分区4槽，未写入容量不代表有效token。'];
  else if(k==='accessCount')calculation=[`本教学帧显式${q.access==='read'?'reads':'writes'}集合长度=${result}，是对象访问条目数量，非硬件指令数或payload条数。`];
  else throw Error('未覆盖metric '+k);
 }else throw Error('未覆盖meta身份 '+key);
 const evidence=deriveMeta(m,q);if(evidence.computed!==undefined&&JSON.stringify(evidence.computed)!==JSON.stringify(result))throw Error('参数/度量显示与推导不符 '+q.objectId);if(evidence.sourceRef)sourceRef=evidence.sourceRef;return {...evidence,objectId:q.objectId,elementPath:p,step:q.step,displayPhase:q.phase||'observe',producerStep:-1,kind:parts[0],unit,origin,operation,operands:evidence.operands||[],calculation:[...calculation,...(evidence.calculation||[])],result,sourceRef,contributions:[],arrayMeaning:'具名参数或索引；非数组区间猜测'};
}
export function numericAccess(m,q){if(q.objectId.startsWith('@'))return 'observe';const f=m.frames[q.step],w=f?.writes.some(w=>w.id===q.objectId);if(w&&fieldProduced(m,q.objectId,q.elementPath||[],f))return 'write';if(f?.reads.some(r=>r.id===q.objectId))return 'read';return 'observe';}

function routeOperands(m,tokens,moment){return tokens.map(t=>({objectId:`R${t.r}.topk_idx[${t.t}]`,elementPath:[],value:t.topk,step:m.config.cached?0:Math.max(0,moment.producerStep),phase:m.config.cached?'previous-fresh-input':'original-input',scope:m.config.cached?'previous-fresh':'current-call'}));}
function receiveSequence(m,r){return m.tokens.filter(t=>tokenRanks(t).includes(r)).map(t=>({...t,slot:rankCountBefore(m,t,r)})).sort((a,b)=>a.r-b.r||a.slot-b.slot);}
function addDerived(out,m,q,moment){const l=m.ledger[q.objectId],obj=l.obj,p=q.elementPath||[],c=m.config,r=l.rank,stage=moment.producer?.stage,t=m.tokens.find(t=>t.r===r&&t.t===Number(l.index));if(typeof out.result!=='number'&&typeof out.result!=='boolean')return;
 const param=k=>({kind:'parameter',objectId:'@config.'+k,elementPath:[],value:c[k],step:0,phase:'initial',sourceRef:src(L,17,'TokenLayout')}),constant=(name,value)=>({kind:'constant',name,value,sourceRef:out.sourceRef});let n,ops=[];
 if(obj==='x'){const h=Number(p[0]),base=c.fp8?(t.gid+1)%4:(t.gid+1)*2;n=t.gid===0||m.tokens.every(t=>t.x.every(v=>v===0))?0:base+(h%(c.fp8?2:4))+(c.cached?32:0);ops=[param('M'),constant('source rank',r),constant('token index',t.t),constant('hidden element index',h)];}
 else if(obj==='topk_idx')n=t.topk[p[0]];
 else if(obj==='topk_weights')n=c.cached?[.25,.75][p[0]]:[.6,.4][p[0]];
 else if(obj==='sf'){n=0x3c00+Number(p[0]);ops=[constant('人工SF基位模式0x3c00',15360),constant('pack index',Number(p[0]))];}
 else if(moment.producerStep<0&&!(['dst_buffer_slot_idx','dst_gsge_idx','recv_src_metadata','psum_num_recv_tokens_per_rank','psum_num_recv_tokens_per_expert','num_unaligned_recv_tokens_per_expert'].includes(obj)&&c.cached)){if(['ub_rank_histogram','ub_expert_histogram','rank_histogram_sum_view','expert_histogram_sum_view','local_rank_histogram','signals'].includes(obj))n=0;else if(obj==='local_copy_dst_slot_idx')n=-1;}
 else if(['rank_histogram_sum_view','ub_rank_histogram','local_rank_histogram'].includes(obj)){
  const core=Number(l.index);if(obj==='local_rank_histogram'&&!p.length)n=0;else if(p[0]==='arrival')n=stage==='prefix'?2:1;else{const d=Number(obj==='local_rank_histogram'?p[1]:p[0]),ts=m.tokens.filter(t=>t.r===r&&(obj==='rank_histogram_sum_view'||stage==='prefix'?t.t<(obj==='rank_histogram_sum_view'?c.T:core):t.t===core));n=ts.reduce((n,t)=>n+(tokenRanks(t).includes(d)?1:0),0);ops=routeOperands(m,ts,moment);ops.push(constant('destination rank',d),param('E'),param('R'),param('T'));}}
 else if(['ub_expert_histogram','expert_histogram_sum_view'].includes(obj)){const core=Number(l.index),max=obj==='ub_expert_histogram'?core+1:moment.producer?.writes.reduce((mx,w)=>m.ledger[w.id]?.obj==='ub_expert_histogram'?Math.max(mx,Number(m.ledger[w.id].index)+1):mx,0)||c.T,ts=m.tokens.filter(t=>t.r===r&&t.t<max&&(obj!=='ub_expert_histogram'||t.t===core));n=ts.reduce((n,t)=>n+t.topk.filter(e=>e===Number(p[0])).length,0);ops=routeOperands(m,ts,moment);}
 else if(obj==='num_unaligned_recv_tokens_per_expert'||obj==='psum_num_recv_tokens_per_expert'){const e=Number(p[0]);n=obj.startsWith('psum')?(e?align(expertCount(m,r,0),c.A):0)+expertCount(m,r,e):expertCount(m,r,e);ops=routeOperands(m,m.tokens,moment);ops.push(param('A'),constant('local expert',e),constant('destination rank',r));}
 else if(obj==='psum_num_recv_tokens_per_rank'){n=Array.from({length:Number(p[0])+1},(_,s)=>rankCount(m,s,r)).reduce((a,b)=>a+b,0);ops=routeOperands(m,m.tokens.filter(t=>t.r<=Number(p[0])),moment);}
 else if(['dst_buffer_slot_idx','dst_gsge_idx','local_copy_dst_slot_idx'].includes(obj)){let j=obj==='local_copy_dst_slot_idx'?t.topk.findIndex(e=>e>=0&&Math.floor(e/2)===r):Number(p[0]),e=t.topk[j],d=e>=0?Math.floor(e/2):-1,dup=j>=0&&t.topk.slice(0,j).some(e=>e>=0&&Math.floor(e/2)===d);n=e===undefined||e<0||dup?-1:obj==='dst_gsge_idx'?(d===r?-1:tokenRanks(t).filter(x=>x!==r).sort((a,b)=>(a-r+4)%4-(b-r+4)%4).indexOf(d)*6):rankCountBefore(m,t,d);ops=routeOperands(m,m.tokens.filter(x=>x.r===r&&x.t<=t.t),moment);ops.push(constant('top-k lane',j),constant('max SGEPairs/SQE',6));}
 else if(obj==='metadata_send_buffer'){if(p[0]==='src_global_idx'){n=r*c.M+t.t;ops=[constant('source rank',r),param('M'),constant('token index',t.t)];}else{const source=p[0]==='topk'?'topk_idx':p[0]==='weights'?'topk_weights':'sf',id=`R${r}.${source}[${t.t}]`;n=at(m.frames[0].snapshot[id],p.slice(1));}}
 else if(obj==='epilogue_expert_counter'){const seq=receiveSequence(m,r),e=r*2+Number(p[1]);n=seq.slice(0,Number(p[0])).reduce((n,t)=>n+t.topk.filter(x=>x===e).length,0);ops=routeOperands(m,seq.slice(0,Number(p[0])),moment);ops.push(constant('global expert',e));}
 else if(obj==='recv_src_metadata'){const seq=receiveSequence(m,r),pos=Number(l.index),rec=seq[pos],j=Number(p[0]);if(j===2)n=rec.r*c.M+rec.t;else if(j===3)n=rec.topk.map((e,j)=>e>=r*2&&e<r*2+2?j:-1).filter(j=>j>=0).at(-1)??-1;else{const e=rec.topk[j],le=e-r*2;n=le<0||le>=2?-1:(le?align(expertCount(m,r,0),c.A):0)+seq.slice(0,pos).filter(t=>t.topk.includes(e)).length;}ops=routeOperands(m,m.tokens,moment);ops.push(param('A'),param('M'),constant('recv stream position',pos),constant('metadata field index',j));}
 else if(obj==='SQE'){const i=Number(p[0]),peers=tokenRanks(t).filter(d=>d!==r).sort((a,b)=>(a-r+4)%4-(b-r+4)%4),d=peers[i],slot=rankCountBefore(m,t,d),f=p[1];n={logicalSQE:i,physicalSQE:i,dst_rank:d,dst_slot:slot,remote_offset:(r*c.M+slot)*c.tokenBytes,num_sges:2,validWQEBBs:Math.ceil((48+2*16)/64),reservedWQEBBs:4,finalFlags:i===peers.length-1}[f];if(f==='SGEs')n=Number(p[2])===0?c.hiddenBytes:c.metadataBytes;ops=routeOperands(m,m.tokens.filter(x=>x.r===r&&x.t<=t.t),moment);ops.push(param('M'),param('tokenBytes'),param('hiddenBytes'),param('metadataBytes'),constant('SQE header bytes',48),constant('SGE bytes',16),constant('WQEBB bytes',64),constant('reserved WQEBBs',4),constant('physical SQE chosen linearization',i));}
 else if(['recv_buffer','recv_x','recv_topk_weights','recv_sf'].includes(obj)){if(stage==='padding'){n=0;ops=[constant('明确padding清零值',0)];}else if(out.operands.length){const o=out.operands[0],f=moment.producer||m.frames[0],read=f.reads.find(x=>x.id===o.objectId),snapshot=m.frames[Math.max(0,moment.producerStep-1)].snapshot;n=at(read?read.value:snapshot[o.objectId],o.elementPath||[]);}}
 else if(obj==='signals'){n=moment.producerStep<0?0:1;ops=[constant('ready发布值',1),{kind:'event',name:'生产条件',value:moment.producer?.title,step:moment.producerStep,sourceRef:out.sourceRef}];}
 if(n!==undefined){out.computed=n;if(JSON.stringify(n)!==JSON.stringify(out.result))throw Error('派生数值不匹配 '+q.objectId+JSON.stringify(p)+' '+JSON.stringify(n)+' vs '+JSON.stringify(out.result));if(ops.length)out.operands=ops;out.derivation={computed:n,operation:out.operation,operands:out.operands};}
}
function copyIdentity(out,m,q){const l=m.ledger[q.objectId],p=q.elementPath||[],field=l.obj==='metadata_send_buffer'?p[0]:l.obj==='recv_buffer'&&p[0]==='metadata'?p[1]:null;if(field==='topk'&&typeof out.result==='number'){out.unit='expert ID / -1无专家选择';out.calculation.push(out.result===-1?'这个-1原样继承无专家选择哨兵；不是槽编号、区间端点或有效expert0。':`expert ${out.result} 是合法选择；floor(${out.result}÷2)=${Math.floor(out.result/2)}表示目的rank，${out.result} mod 2=${out.result%2}表示local expert；有效0仍是expert0。`);}else if(field==='sf'){out.unit='int16 SF pack原始位模式';if(typeof out.result==='number')out.calculation.push(`复制原始pack位模式 ${out.result}=0x${out.result.toString(16)}；不解码为scale，不乘hidden。`);}else if(field==='weights')out.unit='float32 top-k权重';else if(field==='src_global_idx')out.unit='来源全局token索引';}
function deriveMeta(m,q){const c=m.config,key=q.objectId.slice(1).split('.'),group=key[0],k=key[1],constant=(name,value)=>({kind:'constant',name,value,sourceRef:src(L,17)}),parameter=k=>({kind:'parameter',objectId:'@config.'+k,elementPath:[],value:c[k],step:0,phase:'initial',sourceRef:src(L,17)});let computed,sourceRef,calculation=[],operands=[];
 if(group==='config'){const sf=c.sfPacks*2,meta=(sf?align(sf,32):0)+align(c.K*4+(c.cached?0:align(c.K*8,32)+4),32),hidden=c.H*(c.fp8?1:2);computed={hiddenBytes:hidden,sfBytes:sf,metadataBytes:meta,tokenBytes:hidden+meta,regionBytes:c.M*(hidden+meta),bufferBytes:c.R*c.M*(hidden+meta),sfPacks:c.fp8?8:0}[k];if(computed!==undefined){operands=({hiddenBytes:['H','fp8'],sfBytes:['sfPacks'],metadataBytes:['K','cached','sfBytes'],tokenBytes:['hiddenBytes','metadataBytes'],regionBytes:['M','tokenBytes'],bufferBytes:['R','regionBytes'],sfPacks:['fp8']}[k]).map(parameter);const constants={hiddenBytes:[['BF16元素bytes',2],['FP8元素bytes',1]],sfBytes:[['int16 pack bytes',2]],metadataBytes:[['int64专家ID bytes',8],['float32权重bytes',4],['int32 global_idx bytes',4],['UB字节对齐',32]],sfPacks:[['人工选择FP8 pack数量',8],['无SF分支pack数量',0]]};operands.push(...(constants[k]||[]).map(([n,v])=>constant(n,v)));sourceRef=k==='sfPacks'?{file:'animation/model.mjs',line:9,url:'model.mjs',fn:'buildModel',commit:COMMIT}:src(L,36,'TokenLayout::get_num_bytes');}else{computed=c[k];operands=[{kind:'input',name:'教学配置选择 '+k,value:c[k],step:0,sourceRef:{file:'animation/model.mjs',line:8,url:'model.mjs',fn:'buildModel',commit:COMMIT}}];sourceRef={file:'animation/model.mjs',line:8,url:'model.mjs',fn:'buildModel',commit:COMMIT};}}
 else if(group==='metric'){const r=q.rank,e=q.expert,seq=r===undefined?[]:receiveSequence(m,r),t=m.tokens.find(t=>t.key===q.tokenKey);switch(k){case'expertCount':computed=expertCount(m,r,e);sourceRef=src(D,482);break;case'expertStart':computed=e===0?0:align(expertCount(m,r,0),c.A);sourceRef=src(E,426);break;case'recvCount':computed=seq.length;sourceRef=src(E,280);break;case'expandedCount':computed=align(expertCount(m,r,0),c.A)+align(expertCount(m,r,1),c.A);sourceRef=src('csrc/buffers/ep.hpp',313,'EPBuffer::dispatch');break;case'sourceExpertHits':computed=m.tokens.filter(t=>t.r===r).reduce((n,t)=>n+t.topk.filter(e=>e>=0).length,0);sourceRef=src(D,179);break;case'sqeCount':case'sgeCount':computed=tokenRanks(t).filter(d=>d!==t.r).length*(k==='sgeCount'?2:1);sourceRef=src(D,k==='sgeCount'?372:331);break;case'globalIdx':computed=q.sourceRank*c.M+q.token;sourceRef=src(D,779);operands=[constant('source rank',q.sourceRank),parameter('M'),constant('source token',q.token)];break;case'capacitySlots':computed=c.R*c.M;sourceRef=src(L,106,'BufferLayout');operands=[parameter('R'),parameter('M')];break;case'accessCount':computed=m.frames[q.step][q.access==='read'?'reads':'writes'].length;sourceRef={file:'animation/model.mjs',line:43,url:'model.mjs',fn:'frame',commit:COMMIT};operands=[{kind:'event-set',name:q.access==='read'?'本帧reads':'本帧writes',step:q.step,value:m.frames[q.step][q.access==='read'?'reads':'writes'].map(x=>x.id),sourceRef}];break;default:throw Error('未覆盖derived metric '+k);}
  if(!operands.length)operands=routeOperands(m,m.tokens,{producerStep:q.step});calculation.push(`独立重算结果=${computed}；显示值=${q.value}。`);}
 else if(group==='control'){computed=q.value;sourceRef={file:'animation/sync.mjs',line:5,url:'sync.mjs',fn:'connect::effective',commit:COMMIT};operands=[{kind:'input',name:'用户选择的播放间隔毫秒',value:q.value,step:q.step,sourceRef},constant('毫秒/秒',1000)];}
 else if(group==='dtype'){computed=m.ledger[q.object].dtype;sourceRef=ledgerSource(m.ledger[q.object]);operands=[{kind:'type',name:'字段声明dtype',value:computed,sourceRef}];}
 else if(group==='bytes'||group==='shape'){const l=m.ledger[q.object];if(group==='shape')computed=l.shape[q.index];else computed=l.obj==='SQE'?4*64:l.obj==='signals'?0:l.obj==='metadata_send_buffer'?c.metadataBytes:l.obj==='recv_buffer'?c.tokenBytes:l.shape.reduce((a,b)=>a*b,1)*(l.dtype==='int64'?8:l.dtype.includes('int16')?2:l.dtype==='bfloat16'?2:l.dtype==='float8_e4m3fn'?1:4);operands=[{kind:'layout',name:'逻辑shape',value:l.shape,sourceRef:ledgerSource(l)},constant('dtype',l.dtype)];sourceRef=ledgerSource(l);if(l.obj==='SQE'){const list=m.frames[q.step].snapshot[q.object],n=Array.isArray(list)?list.length:null;calculation.push(`此账本shape=[4]和256B是每个SQE的预留布局常数：4 WQEBB ×64B=256B；不是整个SQE[token]列表容量。${n===null?'列表尚未生产，实际数量未知。':`当前列表有${n}个SQE，总预留=${n}×256=${n*256}B。`}`);sourceRef=src(D,423);operands.push(constant('WQEBBs/SQE',4),constant('bytes/WQEBB',64));}}
 else if(group==='index'){computed=q.value;operands=[{kind:'index',name:'界面/对象索引 '+k,value:q.value,step:q.step,sourceRef:src(D,177)}];sourceRef=src(D,k==='hidden'?407:k==='expert'?177:86);}
 return {computed,sourceRef,calculation,operands,scope:group==='bytes'&&m.ledger[q.object]?.obj==='SQE'?'per-SQE-layout':group};
}
function ledgerSource(l){const lines={rank_histogram_sum_view:29,expert_histogram_sum_view:30,psum_num_recv_tokens_per_rank:31,psum_num_recv_tokens_per_expert:32,num_unaligned_recv_tokens_per_expert:33,signals:34,epilogue_expert_counter:35,ub_expert_histogram:36,ub_rank_histogram:36,local_rank_histogram:36,x:38,topk_idx:38,topk_weights:39,sf:39,dst_buffer_slot_idx:40,dst_gsge_idx:40,local_copy_dst_slot_idx:40,metadata_send_buffer:41,SQE:41,recv_buffer:43,recv_src_metadata:44,recv_x:45,recv_topk_weights:45,recv_sf:45};if(!lines[l.obj])throw Error('ledger元数据来源未覆盖 '+l.obj);return {file:'animation/model.mjs',line:lines[l.obj],url:'model.mjs',fn:'buildModel::defs（教学账本声明）',commit:COMMIT};}
function undefinedSource(m,l,p,result){const obj=l.obj,c=m.config,field=obj==='metadata_send_buffer'?p[0]:obj==='recv_buffer'&&p[0]==='metadata'?p[1]:null;if(result===PADDING||field==='padding')return src(L,36,'TokenLayout::get_num_bytes');if(field==='sf'&&c.sfPacks===0)return src(D,697);if(field==='weights'&&!c.weights)return src(D,740);if((field==='topk'||field==='src_global_idx')&&c.cached)return src(D,727);if(c.cached&&['ub_rank_histogram','ub_expert_histogram','rank_histogram_sum_view','expert_histogram_sum_view'].includes(obj))return src(D,155);if(obj==='epilogue_expert_counter')return src(E,329);if(obj==='recv_buffer')return src(E,199);if(obj==='SQE')return src(D,331);const alloc={metadata_send_buffer:202,psum_num_recv_tokens_per_rank:207,psum_num_recv_tokens_per_expert:210,num_unaligned_recv_tokens_per_expert:213,dst_buffer_slot_idx:216,dst_gsge_idx:219,recv_x:323,recv_topk_weights:339,recv_sf:331,recv_src_metadata:342};if(!alloc[obj])throw Error('未定义对象来源未覆盖 '+obj);return src('csrc/buffers/ep.hpp',alloc[obj],'EPBuffer::dispatch');}
