export function connect(role,limit,onChange){
 const session=new URL(location.href).searchParams.get('session')||'dispatch-demo';const channel=new BroadcastChannel('deepep-teaching:'+session);const peer=crypto.randomUUID();
 let owner=false,connected=false,lastSeen=0,state={session,preset:'mixed',step:0,playing:false,duration:1400,anchorStep:0,anchorTime:Date.now(),selected:'0:0',cell:'R0.x[0]',element:0,epoch:0,revision:0,owner:''};
 const effective=()=>state.playing?Math.min(limit(state.preset)-1,state.anchorStep+Math.floor(Math.max(0,Date.now()-state.anchorTime)/state.duration)):state.step;
 const emit=()=>onChange({...state,step:effective(),authoritative:owner,connected,role});
 const broadcast=()=>{channel.postMessage({type:'state',state});lastSeen=Date.now();connected=true;};
 function commit(patch){const step=effective();state={...state,step,anchorStep:step,anchorTime:Date.now(),...patch,epoch:state.epoch,revision:state.revision+1,owner:peer};broadcast();emit();}
 function apply(command){if(!owner)return;switch(command.action){case'play':commit({playing:!state.playing});break;case'pause':commit({playing:false});break;case'step':case'seek':{const step=Math.max(0,Math.min(limit(state.preset)-1,command.action==='step'?effective()+command.value:command.value));commit({step,anchorStep:step,playing:false});break;}case'reset':commit({step:0,anchorStep:0,playing:false});break;case'speed':commit({duration:command.value});break;case'preset':commit({preset:command.value,step:0,anchorStep:0,playing:false,selected:'0:0',cell:'R0.x[0]',element:0});break;case'select':commit({selected:command.key,cell:command.cell||state.cell});break;case'cell':commit({cell:command.value});break;case'element':commit({element:command.value});break;}}
 channel.onmessage=event=>{const msg=event.data;if(msg.type==='hello'){channel.postMessage({type:'state',state});return;}if(msg.type==='command'){apply(msg.command);return;}if(msg.type==='state'&&msg.state.session===session){const x=msg.state;if(x.epoch>state.epoch||(x.epoch===state.epoch&&x.revision>=state.revision)){state=x;connected=!!x.owner;lastSeen=Date.now();emit();}}};
 channel.postMessage({type:'hello'});
 if(role==='control'&&navigator.locks)navigator.locks.request('deepep-owner:'+session,async()=>{await new Promise(r=>setTimeout(r,250));const step=effective();owner=true;state={...state,owner:peer,epoch:Date.now(),revision:1,step,anchorStep:step,anchorTime:Date.now()};broadcast();emit();await new Promise(()=>{});});
 const interval=setInterval(()=>{if(owner){if(state.playing&&effective()===limit(state.preset)-1)commit({playing:false,step:limit(state.preset)-1,anchorStep:limit(state.preset)-1});if(Date.now()-lastSeen>850)broadcast();}else if(Date.now()-lastSeen>2800)connected=false;emit();},100);
 return {session,send:command=>owner?apply(command):channel.postMessage({type:'command',command}),getState:()=>({...state,step:effective(),authoritative:owner,connected}),close:()=>{clearInterval(interval);channel.close();}};
}
